# Generated by Django 6.0.7 on 2026-07-16 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='breve descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
