# Generated by Django 6.0.7 on 2026-07-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='engenheiro_responsavel',
            field=models.CharField(blank=True, max_length=255, verbose_name='engenheiro responsável'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=100, verbose_name='número do contrato'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído')], default='ativo', max_length=16, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='trecho',
            field=models.CharField(blank=True, max_length=255, verbose_name='trecho'),
        ),
    ]
