# Generated by Django 6.0.7 on 2026-07-16 23:14

import buildflow.registros_diarios.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0003_equipe_maquina_pessoa_equipe_encarregado'),
        ('projetos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_referencia', models.DateField(verbose_name='data de referência')),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('noturno', 'Noturno')], max_length=16, verbose_name='turno')),
                ('clima', models.CharField(choices=[('sol', 'Sol'), ('nublado', 'Nublado'), ('chuva', 'Chuva'), ('chuva_forte', 'Chuva forte')], max_length=16, verbose_name='clima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rdos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdos_criados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_diarios', to='configuracoes.equipe', verbose_name='equipe')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdos_como_fiscal', to=settings.AUTH_USER_MODEL, verbose_name='fiscal')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'registro diário',
                'verbose_name_plural': 'registros diários',
                'ordering': ['-data_referencia', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProducaoDiaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rodovia', models.CharField(max_length=255, verbose_name='rodovia')),
                ('sentido', models.CharField(choices=[('crescente', 'Crescente'), ('decrescente', 'Decrescente')], max_length=16, verbose_name='sentido')),
                ('km_inicial', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='km inicial')),
                ('km_final', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='km final')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.disciplina', verbose_name='disciplina')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.catalogoservico', verbose_name='serviço')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.unidade', verbose_name='unidade')),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='registros_diarios.registrodiario', verbose_name='registro diário')),
            ],
            options={
                'verbose_name': 'produção diária',
                'verbose_name_plural': 'produções diárias',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('climatica', 'Climática'), ('interferencia', 'Interferência'), ('seguranca', 'Segurança'), ('logistica', 'Logística'), ('qualidade', 'Qualidade'), ('outro', 'Outro')], max_length=16, verbose_name='tipo')),
                ('recurso_afetado', models.CharField(choices=[('maquinarios', 'Maquinários'), ('mao_de_obra', 'Mão de Obra'), ('materiais', 'Materiais'), ('recursos', 'Recursos'), ('area_frente', 'Área/Frente'), ('outro', 'Outro')], max_length=16, verbose_name='recurso afetado')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='registros_diarios.registrodiario', verbose_name='registro diário')),
            ],
            options={
                'verbose_name': 'ocorrência',
                'verbose_name_plural': 'ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.ImageField(upload_to=buildflow.registros_diarios.models.foto_upload_path, verbose_name='arquivo')),
                ('km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='km')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='registros_diarios.registrodiario', verbose_name='registro diário')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_avulso', models.CharField(blank=True, max_length=255, verbose_name='nome (avulso)')),
                ('funcao', models.CharField(max_length=255, verbose_name='função')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('atestado', 'Atestado')], max_length=16, verbose_name='status')),
                ('origem', models.CharField(choices=[('composicao', 'Composição'), ('avulso', 'Avulso')], max_length=16, verbose_name='origem')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracoes.pessoa', verbose_name='pessoa')),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='registros_diarios.registrodiario', verbose_name='registro diário')),
            ],
            options={
                'verbose_name': 'presença',
                'verbose_name_plural': 'presenças',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('nome_avulso', ''), ('pessoa__isnull', False)), models.Q(('nome_avulso__gt', ''), ('pessoa__isnull', True)), _connector='OR'), name='presenca_pessoa_xor_avulso')],
            },
        ),
        migrations.CreateModel(
            name='ApontamentoMaquina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificacao_avulsa', models.CharField(blank=True, max_length=255, verbose_name='identificação (avulsa)')),
                ('horas_produtivas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='horas produtivas')),
                ('horas_paradas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='horas paradas')),
                ('origem', models.CharField(choices=[('composicao', 'Composição'), ('avulso', 'Avulso')], max_length=16, verbose_name='origem')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracoes.maquina', verbose_name='máquina')),
                ('motivo_parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracoes.motivoparada', verbose_name='motivo da parada')),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='registros_diarios.registrodiario', verbose_name='registro diário')),
            ],
            options={
                'verbose_name': 'apontamento de máquina',
                'verbose_name_plural': 'apontamentos de máquina',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('identificacao_avulsa', ''), ('maquina__isnull', False)), models.Q(('identificacao_avulsa__gt', ''), ('maquina__isnull', True)), _connector='OR'), name='apontamento_maquina_xor_avulso')],
            },
        ),
    ]
