# Generated by Django 6.0.7 on 2026-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_diarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovado em'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aguardando_aprovacao', max_length=24, verbose_name='status'),
        ),
    ]
