# Generated by Django 6.0.7 on 2026-07-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_diarios', '0003_marcar_rdos_existentes_como_aprovados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='km'),
        ),
    ]
