# Generated by Django 6.0.7 on 2026-08-02 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0012_catalogoservico_preco_unitario_disciplina_valor_base'),
        ('projetos', '0003_projeto_engenheiro_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_corte', models.DateField(verbose_name='data de corte')),
                ('status', models.CharField(choices=[('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aguardando_aprovacao', max_length=24, verbose_name='status')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_como_fiscal', to=settings.AUTH_USER_MODEL, verbose_name='fiscal')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'medição',
                'verbose_name_plural': 'medições',
                'ordering': ['-data_corte'],
            },
        ),
        migrations.CreateModel(
            name='ItemMedicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade anterior')),
                ('quantidade_acumulada', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade acumulada')),
                ('quantidade_periodo', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade do período')),
                ('preco_unitario_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço unitário (snapshot)')),
                ('valor_periodo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do período')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_medicao', to='configuracoes.catalogoservico', verbose_name='serviço')),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='medicoes.medicao', verbose_name='medição')),
            ],
            options={
                'verbose_name': 'item de medição',
                'verbose_name_plural': 'itens de medição',
            },
        ),
        migrations.AddConstraint(
            model_name='medicao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aguardando_aprovacao')), fields=('projeto',), name='medicao_pendente_unica_por_projeto'),
        ),
    ]
