# Generated by Django 6.0.7 on 2026-08-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmedicao',
            options={'ordering': ['servico__disciplina__nome', 'servico__nome'], 'verbose_name': 'item de medição', 'verbose_name_plural': 'itens de medição'},
        ),
    ]
