# Generated by Django 6.0.7 on 2026-07-22 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0003_projeto_engenheiro_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RNC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_sequencial', models.PositiveIntegerField(verbose_name='número sequencial')),
                ('data_emissao', models.DateField(verbose_name='data de emissão')),
                ('contratada', models.CharField(max_length=255, verbose_name='contratada')),
                ('categoria', models.CharField(choices=[('terraplenagem', 'Terraplenagem'), ('pavimentacao', 'Pavimentação'), ('contencoes', 'Contenções'), ('oaes', 'OAEs'), ('oacs_e_drenagem', 'OACs e Drenagem'), ('sinalizacao_seguranca', 'Sinalização e Segurança'), ('outros', 'Outros')], max_length=32, verbose_name='categoria')),
                ('origem', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço'), ('pessoal', 'Pessoal'), ('seguranca', 'Segurança'), ('equipamento', 'Equipamento'), ('projeto', 'Projeto')], max_length=16, verbose_name='origem')),
                ('gravidade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=16, verbose_name='gravidade')),
                ('tipo', models.CharField(choices=[('ac', 'Ação Corretiva'), ('ap', 'Ação Preventiva')], max_length=4, verbose_name='tipo')),
                ('item', models.CharField(max_length=255, verbose_name='item')),
                ('subitem', models.CharField(blank=True, max_length=255, verbose_name='subitem')),
                ('norma', models.CharField(blank=True, max_length=255, verbose_name='norma / requisito normativo')),
                ('requisito', models.CharField(blank=True, max_length=255, verbose_name='requisito')),
                ('abrangencia', models.CharField(blank=True, max_length=255, verbose_name='abrangência')),
                ('km', models.CharField(blank=True, max_length=32, verbose_name='km')),
                ('reincidencia', models.BooleanField(default=False, verbose_name='reincidência')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('acao_imediata', models.TextField(blank=True, verbose_name='ação imediata')),
                ('data_implementacao', models.DateField(blank=True, null=True, verbose_name='data de implementação')),
                ('responsavel_implementacao', models.CharField(blank=True, max_length=255, verbose_name='responsável pela implementação')),
                ('causa_metodo', models.BooleanField(default=False, verbose_name='causa: método')),
                ('causa_metodo_detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe: método')),
                ('causa_material', models.BooleanField(default=False, verbose_name='causa: material')),
                ('causa_material_detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe: material')),
                ('causa_mao_de_obra', models.BooleanField(default=False, verbose_name='causa: mão de obra')),
                ('causa_mao_de_obra_detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe: mão de obra')),
                ('causa_maquina', models.BooleanField(default=False, verbose_name='causa: máquina')),
                ('causa_maquina_detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe: máquina')),
                ('causa_medicao', models.BooleanField(default=False, verbose_name='causa: medição')),
                ('causa_medicao_detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe: medição')),
                ('causa_meio_ambiente', models.BooleanField(default=False, verbose_name='causa: meio ambiente')),
                ('causa_meio_ambiente_detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe: meio ambiente')),
                ('data_prazo', models.DateField(blank=True, null=True, verbose_name='data prazo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=16, verbose_name='status')),
                ('eficacia', models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('ineficaz', 'Ineficaz')], max_length=16, verbose_name='eficácia')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='data de conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rncs_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rncs', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'RNC',
                'verbose_name_plural': 'RNCs',
                'ordering': ['-data_emissao', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('risco', models.TextField(blank=True, verbose_name='risco')),
                ('data_limite', models.DateField(verbose_name='data limite')),
                ('responsavel', models.CharField(max_length=255, verbose_name='responsável')),
                ('rnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_corretivas', to='rnc.rnc', verbose_name='RNC')),
            ],
            options={
                'verbose_name': 'ação corretiva',
                'verbose_name_plural': 'ações corretivas',
            },
        ),
        migrations.AddConstraint(
            model_name='rnc',
            constraint=models.UniqueConstraint(fields=('projeto', 'numero_sequencial'), name='rnc_numero_sequencial_unico_por_projeto'),
        ),
    ]
