# Generated by Django 6.0.7 on 2026-07-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='projetos.projeto', verbose_name='projeto'),
        ),
        migrations.AddField(
            model_name='catalogoservico',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='configuracoes.disciplina', verbose_name='disciplina'),
        ),
        migrations.AddField(
            model_name='catalogoservico',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.unidade', verbose_name='unidade'),
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('projeto', 'nome'), name='disciplina_unica_por_projeto'),
        ),
    ]
