# Generated by Django 6.0.7 on 2026-07-16 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_initial'),
        ('projetos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'equipe',
                'verbose_name_plural': 'equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=64, verbose_name='codigo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='configuracoes.equipe', verbose_name='equipe')),
            ],
            options={
                'verbose_name': 'maquina',
                'verbose_name_plural': 'maquinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('funcao', models.CharField(max_length=255, verbose_name='funcao')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='configuracoes.equipe', verbose_name='equipe')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='encarregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_como_encarregado', to='configuracoes.pessoa', verbose_name='encarregado'),
        ),
    ]
