# Generated by Django 6.0.7 on 2026-07-17 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_equipe_maquina_pessoa_equipe_encarregado'),
        ('projetos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorCusto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('mao_de_obra', 'Mão de obra'), ('equipamento', 'Equipamento')], max_length=16, verbose_name='tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_custo', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'valor de custo',
                'verbose_name_plural': 'valores de custo',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_alvo', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='valor alvo')),
                ('peso_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso percentual')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='configuracoes.disciplina', verbose_name='disciplina')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='projetos.projeto', verbose_name='projeto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'constraints': [models.UniqueConstraint(fields=('projeto', 'disciplina'), name='meta_unica_por_disciplina_e_projeto')],
            },
        ),
    ]
