# Generated by Django 6.0.7 on 2026-07-22 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_valorcusto_metamensal'),
        ('projetos', '0003_projeto_engenheiro_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorcusto',
            name='funcao',
            field=models.CharField(blank=True, max_length=255, verbose_name='função'),
        ),
        migrations.AddField(
            model_name='valorcusto',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_custo', to='configuracoes.maquina', verbose_name='máquina'),
        ),
        migrations.AddConstraint(
            model_name='valorcusto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('maquina__isnull', True), ('tipo', 'mao_de_obra')), models.Q(('funcao', ''), ('tipo', 'equipamento')), _connector='OR'), name='valor_custo_funcao_ou_maquina_por_tipo'),
        ),
    ]
