# Generated by Django 6.0.7 on 2026-07-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_rename_quantidade_executada_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoservico',
            name='data_fim_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='data de fim prevista'),
        ),
        migrations.AddField(
            model_name='catalogoservico',
            name='data_inicio_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='data de início prevista'),
        ),
    ]
