# Generated by Django 6.0.7 on 2026-08-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0010_catalogoservico_datas_previstas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdisciplinas', to='configuracoes.disciplina', verbose_name='disciplina pai'),
        ),
    ]
